// apps/web/src/lib/components/videos/VideoStatusBadge.svelte
<script setup lang="ts">
	import type { Video } from '$lib/types/videos';

	export let type: Video['type'];
</script>

{#if type === 'video'}
	<span class="badge badge-neutral">Video</span>
{:else if type === 'short'}
	<span class="badge badge-primary">Short</span>
{:else}
	<span class="badge badge-success">Stream</span>
{/if}

// apps/web/src/components/VideoStatusBadge.vue
<script setup lang="ts">
import type { Video } from '@/lib/types';

const props = defineProps<{
	status: Video['status'];
}>();
</script>

<template>
	<span class="badge badge-success" v-if="props.status === 'live'">Live</span>
	<span class="badge badge-warning" v-else-if="props.status === 'upcoming'">Upcoming</span>
	<span class="badge badge-error" v-else-if="props.status === 'past'">Past</span>
	<span class="badge badge-neutral" v-else>Video</span>
</template>
